server:
  port: 8086

spring:
  application:
    name: VehicleKilometerTracking
  datasource:
    url: jdbc:mysql://localhost:3306/kilometer_db
    username: root
    password: secret
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
